//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 08:15:35 PM MSK 
//


package ru.smsoft.artemis.springbootexample.jaxb.v6_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CitizenshipType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CitizenshipType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="RF"/&gt;
 *     &lt;enumeration value="Foreign"/&gt;
 *     &lt;enumeration value="None"/&gt;
 *     &lt;enumeration value="Both"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CitizenshipType")
@XmlEnum
public enum CitizenshipType {


    /**
     * Гражданство РФ
     * 
     */
    RF("RF"),

    /**
     * Гражданство иного государства
     * 
     */
    @XmlEnumValue("Foreign")
    FOREIGN("Foreign"),

    /**
     * Без гражданства
     * 
     */
    @XmlEnumValue("None")
    NONE("None"),

    /**
     * Гражданство РФ и иного государства
     * 
     */
    @XmlEnumValue("Both")
    BOTH("Both");
    private final String value;

    CitizenshipType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CitizenshipType fromValue(String v) {
        for (CitizenshipType c: CitizenshipType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
