//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 08:15:35 PM MSK 
//


package ru.smsoft.artemis.springbootexample.jaxb.v6_1;

import javax.xml.bind.annotation.*;


/**
 * Запрос документа
 * 
 * <p>Java class for CoordinateTaskMessage complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoordinateTaskMessage"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.w3.org/2000/09/xmldsig#}Signature" minOccurs="0"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="CoordinateTaskDataMessage" type="{http://asguf.mos.ru/rkis_gu/coordinate/v6_1/}CoordinateTaskData"/&gt;
 *           &lt;element name="CoordinateRequest" type="{http://asguf.mos.ru/rkis_gu/coordinate/v6_1/}CoordinateRequestType"/&gt;
 *         &lt;/choice&gt;
 *         &lt;element name="Files" type="{http://asguf.mos.ru/rkis_gu/coordinate/v6_1/}ArrayOfCoordinateFile" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoordinateTaskMessage", propOrder = {
    "signature",
    "coordinateTaskDataMessage",
    "coordinateRequest",
    "files"
})
@XmlSeeAlso({
    CoordinateTaskMessage.class
})
public class CoordinateTaskMessage2 {

    @XmlElement(name = "Signature", namespace = "http://www.w3.org/2000/09/xmldsig#")
    protected SignatureType signature;
    @XmlElement(name = "CoordinateTaskDataMessage")
    protected CoordinateTaskData coordinateTaskDataMessage;
    @XmlElement(name = "CoordinateRequest")
    protected CoordinateRequestType coordinateRequest;
    @XmlElement(name = "Files")
    protected ArrayOfCoordinateFile files;

    /**
     * Gets the value of the signature property.
     * 
     * @return
     *     possible object is
     *     {@link SignatureType }
     *     
     */
    public SignatureType getSignature() {
        return signature;
    }

    /**
     * Sets the value of the signature property.
     * 
     * @param value
     *     allowed object is
     *     {@link SignatureType }
     *     
     */
    public void setSignature(SignatureType value) {
        this.signature = value;
    }

    /**
     * Gets the value of the coordinateTaskDataMessage property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateTaskData }
     *     
     */
    public CoordinateTaskData getCoordinateTaskDataMessage() {
        return coordinateTaskDataMessage;
    }

    /**
     * Sets the value of the coordinateTaskDataMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateTaskData }
     *     
     */
    public void setCoordinateTaskDataMessage(CoordinateTaskData value) {
        this.coordinateTaskDataMessage = value;
    }

    /**
     * Gets the value of the coordinateRequest property.
     * 
     * @return
     *     possible object is
     *     {@link CoordinateRequestType }
     *     
     */
    public CoordinateRequestType getCoordinateRequest() {
        return coordinateRequest;
    }

    /**
     * Sets the value of the coordinateRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link CoordinateRequestType }
     *     
     */
    public void setCoordinateRequest(CoordinateRequestType value) {
        this.coordinateRequest = value;
    }

    /**
     * Gets the value of the files property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfCoordinateFile }
     *     
     */
    public ArrayOfCoordinateFile getFiles() {
        return files;
    }

    /**
     * Sets the value of the files property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfCoordinateFile }
     *     
     */
    public void setFiles(ArrayOfCoordinateFile value) {
        this.files = value;
    }

}
