//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 08:15:35 PM MSK 
//


package ru.smsoft.artemis.springbootexample.jaxb.v6_1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Обращение
 * 
 * <p>Java class for CoordinateData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CoordinateData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Service" type="{http://asguf.mos.ru/rkis_gu/coordinate/v6_1/}RequestService"/&gt;
 *         &lt;element name="SignService" type="{http://asguf.mos.ru/rkis_gu/coordinate/v6_1/}RequestServiceForSign"/&gt;
 *         &lt;element name="Status" type="{http://asguf.mos.ru/rkis_gu/coordinate/v6_1/}RequestStatus" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CoordinateData", propOrder = {
    "service",
    "signService",
    "status"
})
public class CoordinateData {

    @XmlElement(name = "Service", required = true)
    protected RequestService service;
    @XmlElement(name = "SignService", required = true)
    protected RequestServiceForSign signService;
    @XmlElement(name = "Status")
    protected RequestStatus status;

    /**
     * Gets the value of the service property.
     * 
     * @return
     *     possible object is
     *     {@link RequestService }
     *     
     */
    public RequestService getService() {
        return service;
    }

    /**
     * Sets the value of the service property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestService }
     *     
     */
    public void setService(RequestService value) {
        this.service = value;
    }

    /**
     * Gets the value of the signService property.
     * 
     * @return
     *     possible object is
     *     {@link RequestServiceForSign }
     *     
     */
    public RequestServiceForSign getSignService() {
        return signService;
    }

    /**
     * Sets the value of the signService property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestServiceForSign }
     *     
     */
    public void setSignService(RequestServiceForSign value) {
        this.signService = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link RequestStatus }
     *     
     */
    public RequestStatus getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link RequestStatus }
     *     
     */
    public void setStatus(RequestStatus value) {
        this.status = value;
    }

}
