//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 08:15:35 PM MSK 
//


package ru.smsoft.artemis.springbootexample.jaxb.v6_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DigestAlghoritm.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DigestAlghoritm"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="GOST3411-2001"/&gt;
 *     &lt;enumeration value="GOST3411-2012-256"/&gt;
 *     &lt;enumeration value="GOST3411-2012-512"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "DigestAlghoritm")
@XmlEnum
public enum DigestAlghoritm {

    @XmlEnumValue("GOST3411-2001")
    GOST_3411_2001("GOST3411-2001"),
    @XmlEnumValue("GOST3411-2012-256")
    GOST_3411_2012_256("GOST3411-2012-256"),
    @XmlEnumValue("GOST3411-2012-512")
    GOST_3411_2012_512("GOST3411-2012-512");
    private final String value;

    DigestAlghoritm(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DigestAlghoritm fromValue(String v) {
        for (DigestAlghoritm c: DigestAlghoritm.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
