//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 08:15:35 PM MSK 
//


package ru.smsoft.artemis.springbootexample.jaxb.v6_1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;
import java.math.BigDecimal;
import java.math.BigInteger;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.smsoft.efp.core.common.jaxb.efspsign package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {
    private final static QName _Signature_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Signature");
    private final static QName _CoordinateSendTaskStatusesMessage_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "CoordinateSendTaskStatusesMessage");
    private final static QName _GetRequestDocumentsMessage_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "GetRequestDocumentsMessage");
    private final static QName _ServiceHeader_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "ServiceHeader");
    private final static QName _SignatureValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureValue");
    private final static QName _SignedInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignedInfo");
    private final static QName _CanonicalizationMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "CanonicalizationMethod");
    private final static QName _SignatureMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureMethod");
    private final static QName _Reference_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Reference");
    private final static QName _Transforms_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transforms");
    private final static QName _Transform_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Transform");
    private final static QName _DigestMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestMethod");
    private final static QName _DigestValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DigestValue");
    private final static QName _KeyInfo_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyInfo");
    private final static QName _KeyName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyName");
    private final static QName _MgmtData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "MgmtData");
    private final static QName _KeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "KeyValue");
    private final static QName _RetrievalMethod_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RetrievalMethod");
    private final static QName _X509Data_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Data");
    private final static QName _PGPData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPData");
    private final static QName _SPKIData_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKIData");
    private final static QName _Object_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Object");
    private final static QName _Manifest_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "Manifest");
    private final static QName _SignatureProperties_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperties");
    private final static QName _SignatureProperty_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SignatureProperty");
    private final static QName _DSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "DSAKeyValue");
    private final static QName _RSAKeyValue_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "RSAKeyValue");
    private final static QName _Timestamp_QNAME = new QName("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", "Timestamp");
    private final static QName _Expires_QNAME = new QName("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", "Expires");
    private final static QName _Created_QNAME = new QName("http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", "Created");
    private final static QName _SPKIDataTypeSPKISexp_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "SPKISexp");
    private final static QName _PGPDataTypePGPKeyID_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyID");
    private final static QName _PGPDataTypePGPKeyPacket_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "PGPKeyPacket");
    private final static QName _X509DataTypeX509IssuerSerial_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509IssuerSerial");
    private final static QName _X509DataTypeX509SKI_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SKI");
    private final static QName _X509DataTypeX509SubjectName_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509SubjectName");
    private final static QName _X509DataTypeX509Certificate_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509Certificate");
    private final static QName _X509DataTypeX509CRL_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "X509CRL");
    private final static QName _TransformTypeXPath_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "XPath");
    private final static QName _SignatureMethodTypeHMACOutputLength_QNAME = new QName("http://www.w3.org/2000/09/xmldsig#", "HMACOutputLength");
    private final static QName _RequestTypeResponsible_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "Responsible");
    private final static QName _TaskResultXmlView_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "XmlView");
    private final static QName _TaskResultBinaryView_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "BinaryView");
    private final static QName _ServiceDocumentDocDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "DocDate");
    private final static QName _ServiceDocumentValidityPeriod_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "ValidityPeriod");
    private final static QName _ServiceDocumentListCount_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "ListCount");
    private final static QName _ServiceDocumentCopyCount_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "CopyCount");
    private final static QName _RequestServiceForSignCopies_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "Copies");
    private final static QName _RequestServiceServicePrice_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "ServicePrice");
    private final static QName _RequestServicePrepareTargetDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "PrepareTargetDate");
    private final static QName _RequestServiceOutputTargetDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "OutputTargetDate");
    private final static QName _RequestServicePrepareFactDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "PrepareFactDate");
    private final static QName _RequestServiceOutputFactDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "OutputFactDate");
    private final static QName _RequestContactOMSDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "OMSDate");
    private final static QName _RequestContactOMSValidityPeriod_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "OMSValidityPeriod");
    private final static QName _RequestContactRegAddressType_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "RegAddressType");
    private final static QName _RequestAccountOgrnDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "OgrnDate");
    private final static QName _RequestAccountInnDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "InnDate");
    private final static QName _BaseDepartmentTypeName_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "Name");
    private final static QName _DepartmentInn_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "Inn");
    private final static QName _DepartmentOgrn_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "Ogrn");
    private final static QName _DepartmentRegDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "RegDate");
    private final static QName _DepartmentSystemCode_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "SystemCode");
    private final static QName _CoordinateTaskStatusDataStatusNote_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "StatusNote");
    private final static QName _CoordinateTaskStatusDataAsyncTicket_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "AsyncTicket");
    private final static QName _CoordinateTaskStatusDataResult_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "Result");
    private final static QName _CoordinateFileReferenceFileHash_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "FileHash");
    private final static QName _RequestDocumentsDataResponseDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "ResponseDate");
    private final static QName _RequestDocumentsDataPlanDate_QNAME = new QName("http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", "PlanDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.smsoft.efp.core.common.jaxb.efspsign
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CoordinateMessage }
     * 
     */
    public CoordinateMessage createCoordinateMessage() {
        return new CoordinateMessage();
    }

    /**
     * Create an instance of {@link TaskResult }
     * 
     */
    public TaskResult createTaskResult() {
        return new TaskResult();
    }

    /**
     * Create an instance of {@link TaskDataType }
     * 
     */
    public TaskDataType createTaskDataType() {
        return new TaskDataType();
    }

    /**
     * Create an instance of {@link ServiceDocument }
     * 
     */
    public ServiceDocument createServiceDocument() {
        return new ServiceDocument();
    }

    /**
     * Create an instance of {@link RequestServiceForSign }
     * 
     */
    public RequestServiceForSign createRequestServiceForSign() {
        return new RequestServiceForSign();
    }

    /**
     * Create an instance of {@link CoordinateStatusData }
     * 
     */
    public CoordinateStatusData createCoordinateStatusData() {
        return new CoordinateStatusData();
    }

    /**
     * Create an instance of {@link SignatureType }
     * 
     */
    public SignatureType createSignatureType() {
        return new SignatureType();
    }

    /**
     * Create an instance of {@link CoordinateData }
     * 
     */
    public CoordinateData createCoordinateData() {
        return new CoordinateData();
    }

    /**
     * Create an instance of {@link ArrayOfCoordinateFile }
     * 
     */
    public ArrayOfCoordinateFile createArrayOfCoordinateFile() {
        return new ArrayOfCoordinateFile();
    }

    /**
     * Create an instance of {@link CoordinateMessage.Metadata }
     * 
     */
    public CoordinateMessage.Metadata createCoordinateMessageMetadata() {
        return new CoordinateMessage.Metadata();
    }

    /**
     * Create an instance of {@link CoordinateSendTaskStatusesMessage }
     * 
     */
    public CoordinateSendTaskStatusesMessage createCoordinateSendTaskStatusesMessage() {
        return new CoordinateSendTaskStatusesMessage();
    }

    /**
     * Create an instance of {@link CoordinateStatusMessage }
     * 
     */
    public CoordinateStatusMessage createCoordinateStatusMessage() {
        return new CoordinateStatusMessage();
    }

    /**
     * Create an instance of {@link CoordinateTaskMessage }
     * 
     */
    public CoordinateTaskMessage createCoordinateTaskMessage() {
        return new CoordinateTaskMessage();
    }

    /**
     * Create an instance of {@link CoordinateTaskMessage2 }
     * 
     */
    public CoordinateTaskMessage2 createCoordinateTaskMessage2() {
        return new CoordinateTaskMessage2();
    }

    /**
     * Create an instance of {@link CoordinateTaskData }
     * 
     */
    public CoordinateTaskData createCoordinateTaskData() {
        return new CoordinateTaskData();
    }

    /**
     * Create an instance of {@link CoordinateRequestType }
     * 
     */
    public CoordinateRequestType createCoordinateRequestType() {
        return new CoordinateRequestType();
    }

    /**
     * Create an instance of {@link ErrorMessage }
     * 
     */
    public ErrorMessage createErrorMessage() {
        return new ErrorMessage();
    }

    /**
     * Create an instance of {@link ErrorMessageData }
     * 
     */
    public ErrorMessageData createErrorMessageData() {
        return new ErrorMessageData();
    }

    /**
     * Create an instance of {@link RequestDocumentsData }
     * 
     */
    public RequestDocumentsData createRequestDocumentsData() {
        return new RequestDocumentsData();
    }

    /**
     * Create an instance of {@link SendRequestsMessage }
     * 
     */
    public SendRequestsMessage createSendRequestsMessage() {
        return new SendRequestsMessage();
    }

    /**
     * Create an instance of {@link ArrayOfCoordinateData }
     * 
     */
    public ArrayOfCoordinateData createArrayOfCoordinateData() {
        return new ArrayOfCoordinateData();
    }

    /**
     * Create an instance of {@link SendTasksMessage }
     * 
     */
    public SendTasksMessage createSendTasksMessage() {
        return new SendTasksMessage();
    }

    /**
     * Create an instance of {@link ArrayOfCoordinateTaskData }
     * 
     */
    public ArrayOfCoordinateTaskData createArrayOfCoordinateTaskData() {
        return new ArrayOfCoordinateTaskData();
    }

    /**
     * Create an instance of {@link SendTaskStatusesMessages }
     * 
     */
    public SendTaskStatusesMessages createSendTaskStatusesMessages() {
        return new SendTaskStatusesMessages();
    }

    /**
     * Create an instance of {@link ArrayOfCoordinateTaskStatusData }
     * 
     */
    public ArrayOfCoordinateTaskStatusData createArrayOfCoordinateTaskStatusData() {
        return new ArrayOfCoordinateTaskStatusData();
    }

    /**
     * Create an instance of {@link Headers2 }
     * 
     */
    public Headers2 createHeaders2() {
        return new Headers2();
    }

    /**
     * Create an instance of {@link SetFilesAndStatusesMessage }
     * 
     */
    public SetFilesAndStatusesMessage createSetFilesAndStatusesMessage() {
        return new SetFilesAndStatusesMessage();
    }

    /**
     * Create an instance of {@link ArrayOfSetFilesAndStatusesData }
     * 
     */
    public ArrayOfSetFilesAndStatusesData createArrayOfSetFilesAndStatusesData() {
        return new ArrayOfSetFilesAndStatusesData();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link ArrayOfBaseDeclarant }
     * 
     */
    public ArrayOfBaseDeclarant createArrayOfBaseDeclarant() {
        return new ArrayOfBaseDeclarant();
    }

    /**
     * Create an instance of {@link ArrayOfCoordinateFileReference }
     * 
     */
    public ArrayOfCoordinateFileReference createArrayOfCoordinateFileReference() {
        return new ArrayOfCoordinateFileReference();
    }

    /**
     * Create an instance of {@link ArrayOfDictionaryItem }
     * 
     */
    public ArrayOfDictionaryItem createArrayOfDictionaryItem() {
        return new ArrayOfDictionaryItem();
    }

    /**
     * Create an instance of {@link ArrayOfNote }
     * 
     */
    public ArrayOfNote createArrayOfNote() {
        return new ArrayOfNote();
    }

    /**
     * Create an instance of {@link ArrayOfRequestStatus }
     * 
     */
    public ArrayOfRequestStatus createArrayOfRequestStatus() {
        return new ArrayOfRequestStatus();
    }

    /**
     * Create an instance of {@link ArrayOfServiceDocument }
     * 
     */
    public ArrayOfServiceDocument createArrayOfServiceDocument() {
        return new ArrayOfServiceDocument();
    }

    /**
     * Create an instance of {@link ContactAddress }
     * 
     */
    public ContactAddress createContactAddress() {
        return new ContactAddress();
    }

    /**
     * Create an instance of {@link CoordinateFile }
     * 
     */
    public CoordinateFile createCoordinateFile() {
        return new CoordinateFile();
    }

    /**
     * Create an instance of {@link CoordinateFileReference }
     * 
     */
    public CoordinateFileReference createCoordinateFileReference() {
        return new CoordinateFileReference();
    }

    /**
     * Create an instance of {@link CoordinateRequestMessage }
     * 
     */
    public CoordinateRequestMessage createCoordinateRequestMessage() {
        return new CoordinateRequestMessage();
    }

    /**
     * Create an instance of {@link CoordinateTaskStatusData }
     * 
     */
    public CoordinateTaskStatusData createCoordinateTaskStatusData() {
        return new CoordinateTaskStatusData();
    }

    /**
     * Create an instance of {@link Department }
     * 
     */
    public Department createDepartment() {
        return new Department();
    }

    /**
     * Create an instance of {@link DictionaryItem }
     * 
     */
    public DictionaryItem createDictionaryItem() {
        return new DictionaryItem();
    }

    /**
     * Create an instance of {@link DigestType }
     * 
     */
    public DigestType createDigestType() {
        return new DigestType();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Period }
     * 
     */
    public Period createPeriod() {
        return new Period();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link RequestAccount }
     * 
     */
    public RequestAccount createRequestAccount() {
        return new RequestAccount();
    }

    /**
     * Create an instance of {@link RequestContact }
     * 
     */
    public RequestContact createRequestContact() {
        return new RequestContact();
    }

    /**
     * Create an instance of {@link RequestDocument }
     * 
     */
    public RequestDocument createRequestDocument() {
        return new RequestDocument();
    }

    /**
     * Create an instance of {@link RequestResult }
     * 
     */
    public RequestResult createRequestResult() {
        return new RequestResult();
    }

    /**
     * Create an instance of {@link RequestService }
     * 
     */
    public RequestService createRequestService() {
        return new RequestService();
    }

    /**
     * Create an instance of {@link RequestStatus }
     * 
     */
    public RequestStatus createRequestStatus() {
        return new RequestStatus();
    }

    /**
     * Create an instance of {@link RequestType }
     * 
     */
    public RequestType createRequestType() {
        return new RequestType();
    }

    /**
     * Create an instance of {@link SetFilesAndStatusesData }
     * 
     */
    public SetFilesAndStatusesData createSetFilesAndStatusesData() {
        return new SetFilesAndStatusesData();
    }

    /**
     * Create an instance of {@link StatusType2 }
     * 
     */
    public StatusType2 createStatusType2() {
        return new StatusType2();
    }

    /**
     * Create an instance of {@link TaskType }
     * 
     */
    public TaskType createTaskType() {
        return new TaskType();
    }

    /**
     * Create an instance of {@link SignatureValueType }
     * 
     */
    public SignatureValueType createSignatureValueType() {
        return new SignatureValueType();
    }

    /**
     * Create an instance of {@link SignedInfoType }
     * 
     */
    public SignedInfoType createSignedInfoType() {
        return new SignedInfoType();
    }

    /**
     * Create an instance of {@link CanonicalizationMethodType }
     * 
     */
    public CanonicalizationMethodType createCanonicalizationMethodType() {
        return new CanonicalizationMethodType();
    }

    /**
     * Create an instance of {@link SignatureMethodType }
     * 
     */
    public SignatureMethodType createSignatureMethodType() {
        return new SignatureMethodType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link TransformsType }
     * 
     */
    public TransformsType createTransformsType() {
        return new TransformsType();
    }

    /**
     * Create an instance of {@link TransformType }
     * 
     */
    public TransformType createTransformType() {
        return new TransformType();
    }

    /**
     * Create an instance of {@link DigestMethodType }
     * 
     */
    public DigestMethodType createDigestMethodType() {
        return new DigestMethodType();
    }

    /**
     * Create an instance of {@link KeyInfoType }
     * 
     */
    public KeyInfoType createKeyInfoType() {
        return new KeyInfoType();
    }

    /**
     * Create an instance of {@link KeyValueType }
     * 
     */
    public KeyValueType createKeyValueType() {
        return new KeyValueType();
    }

    /**
     * Create an instance of {@link RetrievalMethodType }
     * 
     */
    public RetrievalMethodType createRetrievalMethodType() {
        return new RetrievalMethodType();
    }

    /**
     * Create an instance of {@link X509DataType }
     * 
     */
    public X509DataType createX509DataType() {
        return new X509DataType();
    }

    /**
     * Create an instance of {@link PGPDataType }
     * 
     */
    public PGPDataType createPGPDataType() {
        return new PGPDataType();
    }

    /**
     * Create an instance of {@link SPKIDataType }
     * 
     */
    public SPKIDataType createSPKIDataType() {
        return new SPKIDataType();
    }

    /**
     * Create an instance of {@link ObjectType }
     * 
     */
    public ObjectType createObjectType() {
        return new ObjectType();
    }

    /**
     * Create an instance of {@link ManifestType }
     * 
     */
    public ManifestType createManifestType() {
        return new ManifestType();
    }

    /**
     * Create an instance of {@link SignaturePropertiesType }
     * 
     */
    public SignaturePropertiesType createSignaturePropertiesType() {
        return new SignaturePropertiesType();
    }

    /**
     * Create an instance of {@link SignaturePropertyType }
     * 
     */
    public SignaturePropertyType createSignaturePropertyType() {
        return new SignaturePropertyType();
    }

    /**
     * Create an instance of {@link DSAKeyValueType }
     * 
     */
    public DSAKeyValueType createDSAKeyValueType() {
        return new DSAKeyValueType();
    }

    /**
     * Create an instance of {@link RSAKeyValueType }
     * 
     */
    public RSAKeyValueType createRSAKeyValueType() {
        return new RSAKeyValueType();
    }

    /**
     * Create an instance of {@link X509IssuerSerialType }
     * 
     */
    public X509IssuerSerialType createX509IssuerSerialType() {
        return new X509IssuerSerialType();
    }

    /**
     * Create an instance of {@link TimestampType }
     * 
     */
    public TimestampType createTimestampType() {
        return new TimestampType();
    }

    /**
     * Create an instance of {@link AttributedDateTime }
     * 
     */
    public AttributedDateTime createAttributedDateTime() {
        return new AttributedDateTime();
    }

    /**
     * Create an instance of {@link AttributedURI }
     * 
     */
    public AttributedURI createAttributedURI() {
        return new AttributedURI();
    }

    /**
     * Create an instance of {@link TaskResult.XmlView }
     * 
     */
    public TaskResult.XmlView createTaskResultXmlView() {
        return new TaskResult.XmlView();
    }

    /**
     * Create an instance of {@link TaskDataType.Parameter }
     * 
     */
    public TaskDataType.Parameter createTaskDataTypeParameter() {
        return new TaskDataType.Parameter();
    }

    /**
     * Create an instance of {@link TaskDataType.Metadata }
     * 
     */
    public TaskDataType.Metadata createTaskDataTypeMetadata() {
        return new TaskDataType.Metadata();
    }

    /**
     * Create an instance of {@link ServiceDocument.CustomAttributes }
     * 
     */
    public ServiceDocument.CustomAttributes createServiceDocumentCustomAttributes() {
        return new ServiceDocument.CustomAttributes();
    }

    /**
     * Create an instance of {@link RequestServiceForSign.CustomAttributes }
     * 
     */
    public RequestServiceForSign.CustomAttributes createRequestServiceForSignCustomAttributes() {
        return new RequestServiceForSign.CustomAttributes();
    }

    /**
     * Create an instance of {@link CoordinateStatusData.CustomAttributes }
     * 
     */
    public CoordinateStatusData.CustomAttributes createCoordinateStatusDataCustomAttributes() {
        return new CoordinateStatusData.CustomAttributes();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SignatureType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Signature")
    public JAXBElement<SignatureType> createSignature(SignatureType value) {
        return new JAXBElement<SignatureType>(_Signature_QNAME, SignatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CoordinateSendTaskStatusesMessage }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CoordinateSendTaskStatusesMessage }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "CoordinateSendTaskStatusesMessage")
    public JAXBElement<CoordinateSendTaskStatusesMessage> createCoordinateSendTaskStatusesMessage(CoordinateSendTaskStatusesMessage value) {
        return new JAXBElement<CoordinateSendTaskStatusesMessage>(_CoordinateSendTaskStatusesMessage_QNAME, CoordinateSendTaskStatusesMessage.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestDocumentsData }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RequestDocumentsData }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "GetRequestDocumentsMessage")
    public JAXBElement<RequestDocumentsData> createGetRequestDocumentsMessage(RequestDocumentsData value) {
        return new JAXBElement<RequestDocumentsData>(_GetRequestDocumentsMessage_QNAME, RequestDocumentsData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Headers2 }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Headers2 }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "ServiceHeader")
    public JAXBElement<Headers2> createServiceHeader(Headers2 value) {
        return new JAXBElement<Headers2>(_ServiceHeader_QNAME, Headers2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SignatureValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureValue")
    public JAXBElement<SignatureValueType> createSignatureValue(SignatureValueType value) {
        return new JAXBElement<SignatureValueType>(_SignatureValue_QNAME, SignatureValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignedInfoType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SignedInfoType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignedInfo")
    public JAXBElement<SignedInfoType> createSignedInfo(SignedInfoType value) {
        return new JAXBElement<SignedInfoType>(_SignedInfo_QNAME, SignedInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CanonicalizationMethodType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link CanonicalizationMethodType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "CanonicalizationMethod")
    public JAXBElement<CanonicalizationMethodType> createCanonicalizationMethod(CanonicalizationMethodType value) {
        return new JAXBElement<CanonicalizationMethodType>(_CanonicalizationMethod_QNAME, CanonicalizationMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignatureMethodType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SignatureMethodType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureMethod")
    public JAXBElement<SignatureMethodType> createSignatureMethod(SignatureMethodType value) {
        return new JAXBElement<SignatureMethodType>(_SignatureMethod_QNAME, SignatureMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Reference")
    public JAXBElement<ReferenceType> createReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_Reference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformsType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransformsType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transforms")
    public JAXBElement<TransformsType> createTransforms(TransformsType value) {
        return new JAXBElement<TransformsType>(_Transforms_QNAME, TransformsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransformType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransformType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Transform")
    public JAXBElement<TransformType> createTransform(TransformType value) {
        return new JAXBElement<TransformType>(_Transform_QNAME, TransformType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DigestMethodType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DigestMethodType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestMethod")
    public JAXBElement<DigestMethodType> createDigestMethod(DigestMethodType value) {
        return new JAXBElement<DigestMethodType>(_DigestMethod_QNAME, DigestMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DigestValue")
    public JAXBElement<byte[]> createDigestValue(byte[] value) {
        return new JAXBElement<byte[]>(_DigestValue_QNAME, byte[].class, null, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link KeyInfoType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyInfo")
    public JAXBElement<KeyInfoType> createKeyInfo(KeyInfoType value) {
        return new JAXBElement<KeyInfoType>(_KeyInfo_QNAME, KeyInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyName")
    public JAXBElement<String> createKeyName(String value) {
        return new JAXBElement<String>(_KeyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "MgmtData")
    public JAXBElement<String> createMgmtData(String value) {
        return new JAXBElement<String>(_MgmtData_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KeyValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link KeyValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "KeyValue")
    public JAXBElement<KeyValueType> createKeyValue(KeyValueType value) {
        return new JAXBElement<KeyValueType>(_KeyValue_QNAME, KeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RetrievalMethodType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RetrievalMethodType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RetrievalMethod")
    public JAXBElement<RetrievalMethodType> createRetrievalMethod(RetrievalMethodType value) {
        return new JAXBElement<RetrievalMethodType>(_RetrievalMethod_QNAME, RetrievalMethodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509DataType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link X509DataType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Data")
    public JAXBElement<X509DataType> createX509Data(X509DataType value) {
        return new JAXBElement<X509DataType>(_X509Data_QNAME, X509DataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PGPDataType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link PGPDataType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPData")
    public JAXBElement<PGPDataType> createPGPData(PGPDataType value) {
        return new JAXBElement<PGPDataType>(_PGPData_QNAME, PGPDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SPKIDataType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SPKIDataType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKIData")
    public JAXBElement<SPKIDataType> createSPKIData(SPKIDataType value) {
        return new JAXBElement<SPKIDataType>(_SPKIData_QNAME, SPKIDataType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ObjectType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Object")
    public JAXBElement<ObjectType> createObject(ObjectType value) {
        return new JAXBElement<ObjectType>(_Object_QNAME, ObjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ManifestType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ManifestType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "Manifest")
    public JAXBElement<ManifestType> createManifest(ManifestType value) {
        return new JAXBElement<ManifestType>(_Manifest_QNAME, ManifestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePropertiesType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SignaturePropertiesType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperties")
    public JAXBElement<SignaturePropertiesType> createSignatureProperties(SignaturePropertiesType value) {
        return new JAXBElement<SignaturePropertiesType>(_SignatureProperties_QNAME, SignaturePropertiesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SignaturePropertyType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link SignaturePropertyType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SignatureProperty")
    public JAXBElement<SignaturePropertyType> createSignatureProperty(SignaturePropertyType value) {
        return new JAXBElement<SignaturePropertyType>(_SignatureProperty_QNAME, SignaturePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DSAKeyValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link DSAKeyValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "DSAKeyValue")
    public JAXBElement<DSAKeyValueType> createDSAKeyValue(DSAKeyValueType value) {
        return new JAXBElement<DSAKeyValueType>(_DSAKeyValue_QNAME, DSAKeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RSAKeyValueType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RSAKeyValueType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "RSAKeyValue")
    public JAXBElement<RSAKeyValueType> createRSAKeyValue(RSAKeyValueType value) {
        return new JAXBElement<RSAKeyValueType>(_RSAKeyValue_QNAME, RSAKeyValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimestampType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TimestampType }{@code >}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", name = "Timestamp")
    public JAXBElement<TimestampType> createTimestamp(TimestampType value) {
        return new JAXBElement<TimestampType>(_Timestamp_QNAME, TimestampType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedDateTime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AttributedDateTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", name = "Expires")
    public JAXBElement<AttributedDateTime> createExpires(AttributedDateTime value) {
        return new JAXBElement<AttributedDateTime>(_Expires_QNAME, AttributedDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AttributedDateTime }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link AttributedDateTime }{@code >}
     */
    @XmlElementDecl(namespace = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd", name = "Created")
    public JAXBElement<AttributedDateTime> createCreated(AttributedDateTime value) {
        return new JAXBElement<AttributedDateTime>(_Created_QNAME, AttributedDateTime.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "SPKISexp", scope = SPKIDataType.class)
    public JAXBElement<byte[]> createSPKIDataTypeSPKISexp(byte[] value) {
        return new JAXBElement<byte[]>(_SPKIDataTypeSPKISexp_QNAME, byte[].class, SPKIDataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyID", scope = PGPDataType.class)
    public JAXBElement<byte[]> createPGPDataTypePGPKeyID(byte[] value) {
        return new JAXBElement<byte[]>(_PGPDataTypePGPKeyID_QNAME, byte[].class, PGPDataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "PGPKeyPacket", scope = PGPDataType.class)
    public JAXBElement<byte[]> createPGPDataTypePGPKeyPacket(byte[] value) {
        return new JAXBElement<byte[]>(_PGPDataTypePGPKeyPacket_QNAME, byte[].class, PGPDataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link X509IssuerSerialType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link X509IssuerSerialType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509IssuerSerial", scope = X509DataType.class)
    public JAXBElement<X509IssuerSerialType> createX509DataTypeX509IssuerSerial(X509IssuerSerialType value) {
        return new JAXBElement<X509IssuerSerialType>(_X509DataTypeX509IssuerSerial_QNAME, X509IssuerSerialType.class, X509DataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SKI", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509SKI(byte[] value) {
        return new JAXBElement<byte[]>(_X509DataTypeX509SKI_QNAME, byte[].class, X509DataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509SubjectName", scope = X509DataType.class)
    public JAXBElement<String> createX509DataTypeX509SubjectName(String value) {
        return new JAXBElement<String>(_X509DataTypeX509SubjectName_QNAME, String.class, X509DataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509Certificate", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509Certificate(byte[] value) {
        return new JAXBElement<byte[]>(_X509DataTypeX509Certificate_QNAME, byte[].class, X509DataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "X509CRL", scope = X509DataType.class)
    public JAXBElement<byte[]> createX509DataTypeX509CRL(byte[] value) {
        return new JAXBElement<byte[]>(_X509DataTypeX509CRL_QNAME, byte[].class, X509DataType.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "XPath", scope = TransformType.class)
    public JAXBElement<String> createTransformTypeXPath(String value) {
        return new JAXBElement<String>(_TransformTypeXPath_QNAME, String.class, TransformType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.w3.org/2000/09/xmldsig#", name = "HMACOutputLength", scope = SignatureMethodType.class)
    public JAXBElement<BigInteger> createSignatureMethodTypeHMACOutputLength(BigInteger value) {
        return new JAXBElement<BigInteger>(_SignatureMethodTypeHMACOutputLength_QNAME, BigInteger.class, SignatureMethodType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Person }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Person }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "Responsible", scope = RequestType.class)
    public JAXBElement<Person> createRequestTypeResponsible(Person value) {
        return new JAXBElement<Person>(_RequestTypeResponsible_QNAME, Person.class, RequestType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskResult.XmlView }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TaskResult.XmlView }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "XmlView", scope = TaskResult.class)
    public JAXBElement<TaskResult.XmlView> createTaskResultXmlView(TaskResult.XmlView value) {
        return new JAXBElement<TaskResult.XmlView>(_TaskResultXmlView_QNAME, TaskResult.XmlView.class, TaskResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfCoordinateFileReference }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link ArrayOfCoordinateFileReference }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "BinaryView", scope = TaskResult.class)
    public JAXBElement<ArrayOfCoordinateFileReference> createTaskResultBinaryView(ArrayOfCoordinateFileReference value) {
        return new JAXBElement<ArrayOfCoordinateFileReference>(_TaskResultBinaryView_QNAME, ArrayOfCoordinateFileReference.class, TaskResult.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "DocDate", scope = ServiceDocument.class)
    public JAXBElement<XMLGregorianCalendar> createServiceDocumentDocDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ServiceDocumentDocDate_QNAME, XMLGregorianCalendar.class, ServiceDocument.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "ValidityPeriod", scope = ServiceDocument.class)
    public JAXBElement<XMLGregorianCalendar> createServiceDocumentValidityPeriod(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ServiceDocumentValidityPeriod_QNAME, XMLGregorianCalendar.class, ServiceDocument.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "ListCount", scope = ServiceDocument.class)
    public JAXBElement<Integer> createServiceDocumentListCount(Integer value) {
        return new JAXBElement<Integer>(_ServiceDocumentListCount_QNAME, Integer.class, ServiceDocument.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "CopyCount", scope = ServiceDocument.class)
    public JAXBElement<Integer> createServiceDocumentCopyCount(Integer value) {
        return new JAXBElement<Integer>(_ServiceDocumentCopyCount_QNAME, Integer.class, ServiceDocument.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "ValidityPeriod", scope = RequestStatus.class)
    public JAXBElement<XMLGregorianCalendar> createRequestStatusValidityPeriod(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ServiceDocumentValidityPeriod_QNAME, XMLGregorianCalendar.class, RequestStatus.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "Copies", scope = RequestServiceForSign.class)
    public JAXBElement<Integer> createRequestServiceForSignCopies(Integer value) {
        return new JAXBElement<Integer>(_RequestServiceForSignCopies_QNAME, Integer.class, RequestServiceForSign.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "ServicePrice", scope = RequestService.class)
    public JAXBElement<BigDecimal> createRequestServiceServicePrice(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_RequestServiceServicePrice_QNAME, BigDecimal.class, RequestService.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "PrepareTargetDate", scope = RequestService.class)
    public JAXBElement<XMLGregorianCalendar> createRequestServicePrepareTargetDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestServicePrepareTargetDate_QNAME, XMLGregorianCalendar.class, RequestService.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "OutputTargetDate", scope = RequestService.class)
    public JAXBElement<XMLGregorianCalendar> createRequestServiceOutputTargetDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestServiceOutputTargetDate_QNAME, XMLGregorianCalendar.class, RequestService.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "PrepareFactDate", scope = RequestService.class)
    public JAXBElement<XMLGregorianCalendar> createRequestServicePrepareFactDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestServicePrepareFactDate_QNAME, XMLGregorianCalendar.class, RequestService.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "OutputFactDate", scope = RequestService.class)
    public JAXBElement<XMLGregorianCalendar> createRequestServiceOutputFactDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestServiceOutputFactDate_QNAME, XMLGregorianCalendar.class, RequestService.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "OMSDate", scope = RequestContact.class)
    public JAXBElement<XMLGregorianCalendar> createRequestContactOMSDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestContactOMSDate_QNAME, XMLGregorianCalendar.class, RequestContact.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "OMSValidityPeriod", scope = RequestContact.class)
    public JAXBElement<XMLGregorianCalendar> createRequestContactOMSValidityPeriod(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestContactOMSValidityPeriod_QNAME, XMLGregorianCalendar.class, RequestContact.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RegType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link RegType }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "RegAddressType", scope = RequestContact.class)
    public JAXBElement<RegType> createRequestContactRegAddressType(RegType value) {
        return new JAXBElement<RegType>(_RequestContactRegAddressType_QNAME, RegType.class, RequestContact.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "OgrnDate", scope = RequestAccount.class)
    public JAXBElement<XMLGregorianCalendar> createRequestAccountOgrnDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestAccountOgrnDate_QNAME, XMLGregorianCalendar.class, RequestAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "InnDate", scope = RequestAccount.class)
    public JAXBElement<XMLGregorianCalendar> createRequestAccountInnDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestAccountInnDate_QNAME, XMLGregorianCalendar.class, RequestAccount.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "Name", scope = BaseDepartmentType.class)
    public JAXBElement<String> createBaseDepartmentTypeName(String value) {
        return new JAXBElement<String>(_BaseDepartmentTypeName_QNAME, String.class, BaseDepartmentType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "Inn", scope = Department.class)
    public JAXBElement<String> createDepartmentInn(String value) {
        return new JAXBElement<String>(_DepartmentInn_QNAME, String.class, Department.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "Ogrn", scope = Department.class)
    public JAXBElement<String> createDepartmentOgrn(String value) {
        return new JAXBElement<String>(_DepartmentOgrn_QNAME, String.class, Department.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "RegDate", scope = Department.class)
    public JAXBElement<XMLGregorianCalendar> createDepartmentRegDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_DepartmentRegDate_QNAME, XMLGregorianCalendar.class, Department.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "SystemCode", scope = Department.class)
    public JAXBElement<String> createDepartmentSystemCode(String value) {
        return new JAXBElement<String>(_DepartmentSystemCode_QNAME, String.class, Department.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "StatusNote", scope = CoordinateTaskStatusData.class)
    public JAXBElement<String> createCoordinateTaskStatusDataStatusNote(String value) {
        return new JAXBElement<String>(_CoordinateTaskStatusDataStatusNote_QNAME, String.class, CoordinateTaskStatusData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "AsyncTicket", scope = CoordinateTaskStatusData.class)
    public JAXBElement<String> createCoordinateTaskStatusDataAsyncTicket(String value) {
        return new JAXBElement<String>(_CoordinateTaskStatusDataAsyncTicket_QNAME, String.class, CoordinateTaskStatusData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TaskResult }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TaskResult }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "Result", scope = CoordinateTaskStatusData.class)
    public JAXBElement<TaskResult> createCoordinateTaskStatusDataResult(TaskResult value) {
        return new JAXBElement<TaskResult>(_CoordinateTaskStatusDataResult_QNAME, TaskResult.class, CoordinateTaskStatusData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "FileHash", scope = CoordinateFileReference.class)
    public JAXBElement<byte[]> createCoordinateFileReferenceFileHash(byte[] value) {
        return new JAXBElement<byte[]>(_CoordinateFileReferenceFileHash_QNAME, byte[].class, CoordinateFileReference.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "ResponseDate", scope = RequestDocumentsData.class)
    public JAXBElement<XMLGregorianCalendar> createRequestDocumentsDataResponseDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestDocumentsDataResponseDate_QNAME, XMLGregorianCalendar.class, RequestDocumentsData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "PlanDate", scope = RequestDocumentsData.class)
    public JAXBElement<XMLGregorianCalendar> createRequestDocumentsDataPlanDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestDocumentsDataPlanDate_QNAME, XMLGregorianCalendar.class, RequestDocumentsData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "ResponseDate", scope = CoordinateStatusData.class)
    public JAXBElement<XMLGregorianCalendar> createCoordinateStatusDataResponseDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestDocumentsDataResponseDate_QNAME, XMLGregorianCalendar.class, CoordinateStatusData.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     */
    @XmlElementDecl(namespace = "http://asguf.mos.ru/rkis_gu/coordinate/v6_1/", name = "PlanDate", scope = CoordinateStatusData.class)
    public JAXBElement<XMLGregorianCalendar> createCoordinateStatusDataPlanDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_RequestDocumentsDataPlanDate_QNAME, XMLGregorianCalendar.class, CoordinateStatusData.class, value);
    }

}
