//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.21 at 08:15:35 PM MSK 
//


package ru.smsoft.artemis.springbootexample.jaxb.v6_1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RegType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RegType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Constant"/&gt;
 *     &lt;enumeration value="Temporary"/&gt;
 *     &lt;enumeration value="Fact"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "RegType")
@XmlEnum
public enum RegType {


    /**
     * Адрес регистрации
     * 
     */
    @XmlEnumValue("Constant")
    CONSTANT("Constant"),

    /**
     * Адрес временной регистрации
     * 
     */
    @XmlEnumValue("Temporary")
    TEMPORARY("Temporary"),

    /**
     * Фактический адрес проживания
     * 
     */
    @XmlEnumValue("Fact")
    FACT("Fact");
    private final String value;

    RegType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RegType fromValue(String v) {
        for (RegType c: RegType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
